apiVersion: v2
name: aioc-hospital-scheduling-service
description: AIOC Hospital Scheduling Service (doctors, appointments)
type: application
version: 0.1.0
appVersion: "1.0.0"
dependencies:
  - name: aioc-hospital-base
    version: "0.1.0"
    repository: "file://../aioc-hospital-base"
