# HTTPRoute: Grafana via main-gateway (kube-system). TLS uses aioc-services-tls there.
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: promstack-grafana
  namespace: monitoring
spec:
  parentRefs:
    - name: main-gateway
      namespace: kube-system
      kind: Gateway
      sectionName: http
    - name: main-gateway
      namespace: kube-system
      kind: Gateway
      sectionName: https
  hostnames:
    - grafana.aioc-services.com
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: promstack-grafana
          port: 3000
