# App of Apps for infra charts – apply once: kubectl apply -f argocd/app-of-apps-infra.yaml
# Syncs argocd/applications-infra/ and creates child Applications for cluster infra (monitoring, cert-manager, etc.).
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: aioc-hospital-infra
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/siesta94/aioc-hospital-charts.git
    targetRevision: HEAD
    path: argocd/applications-infra
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
