# ClusterIssuer for Let's Encrypt with DNS-01 (required for wildcard).
# Before applying: create the DNS provider secret (see argocd/TLS.md).
#
# Example for Cloudflare: create secret with your API token
#   kubectl create secret generic cloudflare-api-token -n cert-manager \
#     --from-literal=api-token=YOUR_CLOUDFLARE_API_TOKEN
#
# For other providers see: https://cert-manager.io/docs/configuration/acme/dns01/
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod-dns
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: strahinjatasic@gmail.com   # change to your email (for expiry notices)
    privateKeySecretRef:
      name: letsencrypt-prod-dns-key
    solvers:
      - dns01:
          cloudflare:
            apiTokenSecretRef:
              name: cloudflare-api-token
              key: api-token
              namespace: cert-manager
