apiVersion: v2
name: promstack
description: Prometheus stack (Prometheus, Grafana, Alertmanager, node-exporter, kube-state-metrics) - wrapper for kube-prometheus-stack
type: application
version: 0.1.0
appVersion: "1.0.0"
dependencies:
  - name: kube-prometheus-stack
    version: "55.5.0"
    repository: https://prometheus-community.github.io/helm-charts
